//* I included .H file in order to search wine for this function.
// Also I made four backgrounds to let user choose. When they 
// click go button, the interface will change to whatever they
// selected.
// generated by Fast Light User Interface Designer (fluid) version 1.0302

#ifndef lab3_h
#define lab3_h
#include <FL/Fl.H>
#include "Wine.h"
#include <iostream>
#include <iomanip>
#include <cstdlib>
#include <fstream>
#include <string>
#include <cstring>
#include <sstream>
using namespace std;
Wine parse_line(string line);
void printWine(Wine wine);
#include <FL/Fl_Double_Window.H>
extern Fl_Double_Window *ratewindow;
#include <FL/Fl_Box.H>
extern Fl_Box *background1;
#include <FL/Fl_Button.H>
extern Fl_Button *Return;
#include <FL/Fl_Value_Input.H>
extern Fl_Value_Input *input1;
extern Fl_Value_Input *input2;
#include <FL/Fl_Text_Display.H>
extern Fl_Text_Display *rateshow;
extern Fl_Double_Window *pricewindow;
extern Fl_Box *background2;
extern Fl_Value_Input *input3;
extern Fl_Value_Input *input4;
extern Fl_Text_Display *priceshow;
extern Fl_Button *Return2;
extern Fl_Double_Window *errorWindow;
extern Fl_Double_Window *Home;
extern Fl_Box *background3;
#include <FL/Fl_Group.H>
#include <FL/Fl_Round_Button.H>
extern Fl_Round_Button *Price;
extern Fl_Round_Button *Rating;
extern Fl_Round_Button *quit;
#endif
